# Generated by Django 5.1.7 on 2025-03-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
